### ISSUE TITLE
Better team page organisation

### ISSUE THREAD

**Issue by ajitzero** [csigitam/csigitam.github.io#5]
Currently, we are managing team pages as `team-<YYYY>.html` files.

The next logical step is to use static data files to generate the pages instead.

Possible solutions:
- Use [Jekyll](https://jekyllrb.com/) to retrieve data from YAML files.
- Use [Angular](https://angular.io/) to retrieve data from JSON files.

In our use case, Angular may be overkill for now since we cannot guarantee that every new web dev team will know Angular, nor can we expect them to learn it due to its steep learning curve. In contrast, Jekyll has a much simpler structure and easier to learn.

If there are other ideas, do put them forward. For now, a complete restructuring for this website with Jekyll seems to be the best way to proceed.

*Edit:* We are currently simply using HTML/CSS(Sass) with Bootstrap 4.1.1 which means for any future update, we need to deal with HTML tags. Jekyll or Angular use data files to generate the file (in Jekyll's case) or dynamically update the file (in Angular's case).

**Comment by ajitzero** [comment]
@anandabhishek01555 @likhithnemani Let me know your thoughts.

**Comment by anandabhishek01555** [comment]
We are not familiar with Jekyll instead . Since you say the code will be simpler in Jekyll , I think we should with that .

**Comment by ajitzero** [comment]
Simpler as compared to Angular.

Jekyll uses plain HTML in all files and allows us to divide components into separate files. That way we can have a file called `team.yml` which could be:

```yaml
- 2019
  - Aditya
    - Vice President
    - LinkedIn: URL...
    - key: value...
  - Ajit
    - Treasurer
    - LinkedIn: URL...
    - key: value...
  - ...
- 2018
  - Aditya
    - Vice President
    - LinkedIn: URL...
    - key: value...
  - Ajit
    - Treasurer
    - LinkedIn: URL...
    - key: value...
  - ...
- 2017
  - ...
```

We can then use this file to loop over the data and generate an HTML file. Later you can simply update the data file & HTML updates automatically. Check out their [official website](https://jekyllrb.com/) for learning more about how it can help us.
